server:
  port: 9090

spring:
  cors:
    allowed-origins: "http://localhost:3000" # aquí puedes especificar los orígenes permitidos, separados por comas
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers: "*" # aquí puedes especificar los headers permitidos
    max-age: 3600 # aquí puedes especificar la duración en segundos del pre-flight request cache

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: alumno-service
          uri: lb://alumno-service
          predicates:
            - Path=/alumno/**
        - id: curso-service
          uri: lb://curso-service
          predicates:
            - Path=/curso/**
        - id: docente-service
          uri: lb://docente-service
          predicates:
            - Path=/docente/**
        - id: inscripccion-service
          uri: lb://inscripccion-service
          predicates:
            - Path=/inscripccion/**
        



